### ISSUE TITLE
Peer Review - Read Me

### ISSUE THREAD

**Issue by bommezijn** [AllyssaA/Functional-Programming#1]
### Welke onderdeel
[readme.md](https://github.com/AllyssaA/Functional-Programming/blob/main/README.md)
### Probleem
Naar mijn gevoel kan hier meer informatie over het project. 
### Voorstel

- [x] Een doel beschrijven, wat er bereikt zal worden na dit project is afgelopen (Het leren en schrijven van Functioneel programmeren met opschoning van data)
- [x] Een demo weergeven van wat het resultaat is. E.G. een screenshot van de opgeschoonde data. (of code snippet)
- [x] Features van dit project, dus wat het op dit moment allemaal doet, of gaat doen (ooit).

**Comment by bommezijn** [comment]
Zag dat je al was begonnen met het invullen van wat het doel van dit project was in commit 7dd837c.

**Comment by AllyssaA** [comment]
Added!
