### ISSUE TITLE
Peer Review - Index.js

### ISSUE THREAD

**Issue by bommezijn** [AllyssaA/Functional-Programming#3]
### Welke onderdeel
[index.js](https://github.com/AllyssaA/Functional-Programming/blob/main/index.js)
### Probleem
Naar mijn gevoel kan je de code verbeteren met de volgende acties.
### Voorstel

- [x] Ik zie dat je commentaar bij iedere functie of comment plaatst, Je zou dit kunnen uitbreiden daar doc comments. Voor referentie wat dit allemaal kan: [jsdoc.app](https://jsdoc.app/). TL;DR indien je enkele tags bij iedere comment plaatst en een command uitvoert, genereer je documentatie voor iedere functie, methode of dergelijke.
  ```JS
  /** 
   @title een voorbeeld doc comment
   @param {String} string een voorbeeld van hoe een param beschreven kan worden
   @returns {TYPE} Wat de functie terug stuurt wanneer de code block is uitgevoerd
  */
  ```
  Hoe je jsdoc gebruikt in je projecten kan je het beste lezen op hun eigen [github pagina jsdoc](https://github.com/jsdoc/jsdoc)
- [x] Op dit moment gebruik je twee manieren van functies declareren, om je code netjes en leesbaar te houden raad ik je aan om één manier te gebruiken, arrow functions (expression) of function declaration.
Het volgende artikel legt naar mijn opinie goed uit wat het verschil is en wanneer je de een over de ander zou gebruiken.
https://github.com/AllyssaA/Functional-Programming/blob/7dd837c5c5618bec33e5f225b85ccd37063808d2/index.js#L12-L20
https://dmitripavlutin.com/differences-between-arrow-and-regular-functions/
- [x] Ook raad ik je aan om een linter / formatter te gebruiken via een NPM/YARN package. Hiermee zorg je ervoor dat je code een bepaalde stijl aanhoudt. Er zijn vele linters en formatters op de markt. dus het is een kwestie van preferentie. [ESlint](https://eslint.org/) is het meest populair maar ook erg uitgebreid, Nicky Meuleman heeft een duidelijke artikel geschreven om linting en formatting toe te passen op je code.
https://nickymeuleman.netlify.app/blog/automagically-lint

**Comment by bommezijn** [comment]
Mocht je vragen hebben over bepaalde onderwerpen of discussies voeren dan kan je mij altijd benaderen 😊

**Comment by AllyssaA** [comment]
Thanks @bommezijn ik heb het allemaal toegepast!
